// Generated by openapi-typescript. Do not edit manually.
// @ts-nocheck

export type components = {
  schemas: {
    Employee: {
      id: number
      name: string
      email: string
      department: string
      created_at: string
    }
    AddEmployeeRequest: {
      name: string
      email: string
      department: string
    }
    ValidationError: {
      field: string
      message: string
    }
    ValidationErrors: {
      errors: components["schemas"]["ValidationError"][]
    }
    AddEmployeeResponse: {
      name: string
      email: string
      department: string
    }
    UpdateEmployeeResponse: {
      id: number
      name: string
      email: string
      department: string
    }
    DeleteResponse: {
      message: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = {}
export type paths = {
  "/employees": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: never
      responses: {
        /** @description OK */
        200: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["Employee"][] }
        }
      }
    }
    put: {
      parameters: never
      requestbody?: {
        content: {
          "application/json": components["schemas"]["AddEmployeeRequest"]
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["AddEmployeeResponse"] }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["ValidationErrors"] }
        }
      }
    }
    post: never
    delete: never
    options: never
    head: never
    patch: never
    trace: never
  }
  "/employees/{id}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        path: { id: string }
      }
      responses: {
        /** @description OK */
        200: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["Employee"] }
        }
        /** @description Not Found */
        404: {
          headers: { [name: string]: unknown }
          content: { "application/json": { error: string } }
        }
      }
    }
    put: {
      parameters: {
        path: { id: string }
      }
      requestbody?: {
        content: {
          "application/json": components["schemas"]["AddEmployeeRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["UpdateEmployeeResponse"] }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["ValidationErrors"] }
        }
      }
    }
    post: never
    delete: {
      parameters: {
        path: { id: string }
      }
      responses: {
        /** @description OK */
        200: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["DeleteResponse"] }
        }
      }
    }
    options: never
    head: never
    patch: never
    trace: never
  }
  "/employees/email/{email}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        path: { email: string }
      }
      responses: {
        /** @description OK */
        200: {
          headers: { [name: string]: unknown }
          content: { "application/json": components["schemas"]["Employee"] }
        }
        /** @description Not Found */
        404: {
          headers: { [name: string]: unknown }
          content: { "application/json": { error: string } }
        }
      }
    }
    put: never
    post: never
    delete: never
    options: never
    head: never
    patch: never
    trace: never
  }
}
export type webhooks = never
export type globalParameters = {
  query: never
  header: never
  path: never
  cookie: never
}
