// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
)

const addEmployee = `-- name: AddEmployee :exec
INSERT INTO employees (name, email, department) 
VALUES ($1, $2, $3)
`

type AddEmployeeParams struct {
	Name       string `json:"name"`
	Email      string `json:"email"`
	Department string `json:"department"`
}

func (q *Queries) AddEmployee(ctx context.Context, arg AddEmployeeParams) error {
	_, err := q.db.Exec(ctx, addEmployee, arg.Name, arg.Email, arg.Department)
	return err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, name, email, department, created_at FROM employees
`

func (q *Queries) ListEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Department,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const employeeById = `-- name: EmployeeById :one
SELECT id, name, email, department, created_at FROM employees
    WHERE id = $1
`

func (q *Queries) EmployeeById(ctx context.Context, id int32) (Employee, error) {
	row := q.db.QueryRow(ctx, employeeById, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.CreatedAt,
	)
	return i, err
}

const employeeByEmail = `-- name: EmployeeByEmail :one
SELECT id, name, email, department, created_at FROM employees
    WHERE email = $1
`

func (q *Queries) EmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, employeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Department,
		&i.CreatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :exec
UPDATE employees
SET name = $2, email = $3, department = $4
WHERE id = $1
`

type UpdateEmployeeParams struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	Department string `json:"department"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.Exec(ctx, updateEmployee,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Department,
	)
	return err
}
