// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	AddEmployee(ctx context.Context, arg AddEmployeeParams) error
	DeleteEmployee(ctx context.Context, id int32) error
	EmployeeByEmail(ctx context.Context, email string) (Employee, error)
	EmployeeById(ctx context.Context, id int32) (Employee, error)
	ListEmployees(ctx context.Context) ([]Employee, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
}

var _ Querier = (*Queries)(nil)
