// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	AddProduct(ctx context.Context, arg AddProductParams) error
	DeleteProduct(ctx context.Context, id int32) error
	ListProducts(ctx context.Context) ([]Product, error)
	ProductById(ctx context.Context, id int32) (Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
